name = "booth-game"
compatibility_date = "2024-11-11"
compatibility_flags = ["nodejs_compat"]

[assets]
directory = "public"
binding = "ASSETS"

[[d1_databases]]
binding = "DB"
database_name = "slicey-game-db"
database_id = "8f193f97-7acc-4ff7-a64a-9e3aac6a8e29"
migrations_dir = "drizzle/migrations"

# [vars]
# MY_VAR = "my-variable"

# Workers Logs
# Docs: https://developers.cloudflare.com/workers/observability/logs/workers-logs/
# Configuration: https://developers.cloudflare.com/workers/observability/logs/workers-logs/#enable-workers-logs
[observability]
enabled = true

# [[kv_namespaces]]
# binding = "MY_KV_NAMESPACE"
# id = "xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx"

# [[r2_buckets]]
# binding = "MY_BUCKET"
# bucket_name = "my-bucket"

# [ai]
# binding = "AI"

[[durable_objects.bindings]]
name = "WebsocketServer"
class_name = "WebsocketServer"

[[migrations]]
tag = "v1"
new_sqlite_classes = ["WebsocketServer"]
